package com.etcc.csc.service;

import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.etcc.csc.common.BusinessObjectInterface;
import com.etcc.csc.common.ErrorMessageDTO;
import com.etcc.csc.common.EtccException;
import com.etcc.csc.common.EtccSecurityException;
import com.etcc.csc.datatype.PlanDetailBalances;
import com.etcc.csc.dto.AccountCardDTO;
import com.etcc.csc.dto.AccountDTO;
import com.etcc.csc.dto.AccountIopDTO;
import com.etcc.csc.dto.AccountLoginDTO;
import com.etcc.csc.dto.OnlineAccessSetupDTO;
import com.etcc.csc.dto.TagDTO;
import com.etcc.csc.dto.TagUpdateResultDTO;
import com.etcc.csc.dto.UserEnvDTO;
import com.etcc.csc.dto.UserPreferenceDTO;
import com.etcc.csc.dto.UserPreferenceResultDTO;

/**
 * Contains methods for managing user accounts.
 */
public interface AccountInterface extends BusinessObjectInterface {

	/**
	 * Validates if an account exists.
	 * 
	 * @param accountNumber
	 * @param tolltagPrefix
	 * @param tolltagNumber
	 * @param driverLicenseState
	 * @param driverLicenseNumber
	 * @param taxId
	 * @return Returns AccountLoginDTO containing the user's account info. If the acctId is empty,
	 *         this indicates that the account does not exist.
	 * @throws EtccException
	 */
	AccountLoginDTO accountExists(String accountNumber, String tolltagPrefix, String tolltagNumber,
			String driverLicenseState, String driverLicenseNumber, String taxId)
			throws EtccException;

	/**
	 * Validates if the account exists and logs the user to the database.
	 * 
	 * @param accountNumber
	 * @param tolltagPrefix
	 * @param tolltagNumber
	 * @param driverLicenseState
	 * @param driverLicenseNumber
	 * @param taxId
	 * @param ipAddress
	 * @param sessionId
	 * @param userEnvDto
	 * @return
	 * @throws EtccException
	 */
	public AccountLoginDTO setupOnlineAccessStep1(String acctCard, String accountNumber,
			String tolltagPrefix, String tolltagNumber, String driverLicenseState,
			String driverLicenseNumber, String taxId, String ipAddress, String sessionId,
			UserEnvDTO userEnvDto, String locale) throws EtccException;

	/**
	 * Performs the setup of online access account.
	 * 
	 * @param oasDto
	 * @return Returns an AccountLoginDTO. It contains the new db session id created by the
	 *         database. If unsuccessful, the errors property contains the error messages.
	 * @throws EtccException
	 */
	AccountLoginDTO setupOnlineAccess(AccountLoginDTO acctLoginDto, OnlineAccessSetupDTO oasDto)
			throws EtccSecurityException, EtccException;

	/**
	 * Validates if the account matches what's in the database.
	 * 
	 * @param userName
	 * @param password
	 * @param ipAddress
	 * @return
	 * @throws EtccException
	 */
	AccountLoginDTO validateAccount(String userName, String password, String ipAddress)
			throws EtccException;

	/**
	 * Logs the account in the database. This is the first step for subsequent user requests to the
	 * database.
	 * 
	 * @param userName
	 * @param password
	 * @param ipAddress
	 * @param sessionId The id given by the web server for this user session.
	 * @return AccountLoginDTO containing the account id and db session id generated by the
	 *         database.
	 * @throws EtccException
	 */
	AccountLoginDTO loginAccount(String userName, String password, String ipAddress,
			String sessionId, UserEnvDTO userEnvDto) throws EtccException;

	/**
	 * Retrieves the account information given an account id.
	 * 
	 * @param acctLoginDto Must satisfy security credential to retrieve this record.
	 * @param AcctId
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException Thrown when the security verification fails.
	 */
	AccountDTO getAccount(AccountLoginDTO acctLoginDto, long AcctId) throws EtccException,
			EtccSecurityException;

	/**
	 * Retrieves the account information given an account id.
	 * 
	 * @param acctLoginDto Must satisfy security credential to retrieve this record.
	 * @param AcctId
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException Thrown when the security verification fails.
	 */
	AccountDTO getNewAccount(AccountLoginDTO acctLoginDto, long AcctId) throws EtccException,
			EtccSecurityException;

	/**
	 * Similar to getAccountTags of AccountHistory only that it returns a Collection of TagDTO
	 * instead of the Oracle-generated class.
	 * 
	 * @param acctLoginDto
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection getAccountTags(AccountLoginDTO acctLoginDto) throws EtccException,
			EtccSecurityException;

	/**
	 * Similar to getAccountTags of AccountHistory only that it returns a Collection of TagDTO
	 * instead of the Oracle-generated class.
	 * 
	 * @param acctLoginDto
	 * @param searchString
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection getAccountTagsBySearch(AccountLoginDTO acctLoginDto, String[] searchArr)
			throws EtccException, EtccSecurityException;

	/**
	 * Similar to getAccountTags of AccountHistory only that it returns a Collection of TagDTO
	 * instead of the Oracle-generated class.
	 * 
	 * @param acctLoginDto
	 * @param searchString
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	List<TagDTO> getProposedAccountTags(AccountLoginDTO acctLoginDto)
			throws EtccException, EtccSecurityException;

	/**
	 * Saving account cards request
	 * 
	 * @param acctLoginDto
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	boolean saveAccountCardRequest(AccountLoginDTO acctLoginDto, int numOfUnits)
			throws EtccException, EtccSecurityException;

	/**
	 * Retrieving the account cards info
	 * 
	 * @param acctLoginDto
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Map<String, Integer> getAccountCardInfo(AccountLoginDTO acctLoginDto) throws EtccException,
			EtccSecurityException;

	/**
	 * Retrieving account card detail info
	 * 
	 * @param acctLoginDto
	 * @param locale TODO
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection<AccountCardDTO> getAccountCardDetailInfo(AccountLoginDTO acctLoginDto, String locale) throws EtccException,
			EtccSecurityException;

	/**
	 * Retrieving the reason codes for card removals.
	 * 
	 * @param acctLoginDto
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection getAccountReasonCodes(AccountLoginDTO acctLoginDto) throws EtccException,
			EtccSecurityException;

	/**
	 * Removing account card from account
	 * 
	 * @param acctLoginDto
	 * @param acctCardDto
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	int removeAccountCard(AccountLoginDTO acctLoginDto, AccountCardDTO acctCardDto)
			throws EtccException, EtccSecurityException;

	/**
	 * Retrieves the user's preferences from the database.
	 * 
	 * @param acctLoginDto Contains the user's login credentials.
	 * @return Returns a collection of UserPreferenceDTO.
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	UserPreferenceResultDTO getUserPreference(AccountLoginDTO acctLoginDto) throws EtccException,
			EtccSecurityException;

	/**
	 * Retrieves the user preference options for customers applying for a tolltag.
	 * 
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	UserPreferenceResultDTO getTollTagUserPreference(String locale) throws EtccException,
			EtccSecurityException;

	/**
	 * Persists the changes to the user preference to the database.
	 * 
	 * @param acctLoginDto
	 * @param userPrefResult
	 * @throws EtccException
	 * @throws EtccSecurityException
	 * @return True if operation is successful, false, otherwise.
	 */
	Collection<ErrorMessageDTO> updateUserPreference(AccountLoginDTO acctLoginDto, AccountIopDTO[] acctIops,
			UserPreferenceDTO[] userPrefs) throws EtccException, EtccSecurityException;

	/**
	 * Saves the changes to an existing account.
	 * 
	 * @param accountDto Account Information.
	 * @return Returns a collection of error messages.
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection updateAccount(AccountLoginDTO acctLoginDto, AccountDTO accountDto)
			throws EtccException, EtccSecurityException;

	/**
	 * Updates the account's tag information.
	 * 
	 * @param acctLoginDto Login credentials.
	 * @param tags A collection of TagDTO to update.
	 * @param checkDuplicate Flag to determine if duplicates are to be checked. Record will not be
	 *            updated if a duplicate license plate is found and the flag is set to true.
	 * @return Returns TagUpdateResultDTO containing the result of the operation, collection of
	 *         errors, and duplicate license tags.
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	TagUpdateResultDTO updateAccountTags(AccountLoginDTO acctLoginDto, TagDTO[] tags,
			boolean checkDuplicate) throws EtccException, EtccSecurityException;

	/**
	 * Retrieves the alerts for the given account.
	 * 
	 * @param acctLoginDto
	 * @param pageContext TODO
	 * @return Returns a collection of AlertDTO.
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection getAlerts(AccountLoginDTO acctLoginDto, String pageContext) throws EtccException, EtccSecurityException;

	/**
	 * Retrieves the previous x transactions for the given account.
	 * 
	 * @param acctLoginDto
	 * @return
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	Collection getLastTransactions(AccountLoginDTO acctLoginDto)
			throws EtccException, EtccSecurityException;

	/**
	 * Checks whether the account has an outstanding payment given a retail transaction id, or given
	 * a collection of license plates, if there are violations that need to be settled.s
	 * 
	 * @param acctLoginDto
	 * @param transId Retail transaction ID. Generated when a toll tag is ordered.
	 * @param licensePlates A collection of TagDTOs.
	 * @return True if the account owes something, false otherwise.
	 * @throws EtccException
	 * @throws EtccSecurityException
	 */
	boolean isPaymentOwed(AccountLoginDTO acctLoginDto, long transId, TagDTO[] licensePlates)
			throws EtccException, EtccSecurityException;

	boolean isBigAccount(long accountId);

	void resetEmailAddressValid(AccountLoginDTO acctLoginDto, String emailAddress);

	int isVerificationRequired(AccountLoginDTO acctLoginDto);

	int verifyAccount(AccountLoginDTO acctLoginDto);

	int isEnoughtSecurityQuestions(AccountLoginDTO acctLoginDto);

	String getIntialPrepaidBalanceDetails(AccountLoginDTO acctLoginDto);

	List<PlanDetailBalances> getPlanDetailBalances(long planDetailId) throws EtccException,
			EtccSecurityException;

	Double getItemPriceByInventoryTypeIdAndDate(AccountLoginDTO acctLoginDto, Long inventoryTypeId,
			Date date)
			throws EtccException, EtccSecurityException;

	Double getTagSalePriceByItemType(AccountLoginDTO acctLoginDto, long inventoryTypeId, Date date)
			throws EtccException, EtccSecurityException;

	public String getAutoChargeAmounts(AccountLoginDTO acctLoginDto) throws Exception;

	public double getTagDepositAmout(AccountLoginDTO accountLoginDTO) throws Exception;
	
	public double getCancelFulfillmentTagDepositAmout(AccountLoginDTO accountLoginDTO, String fulfillmentID) throws Exception;
	
	public Collection getInvoiceDetails(AccountLoginDTO acctLoginDto)  throws Exception;


}
