<%-- 
  - Author(s): Noel Ternida
  - Date: April 26, 2006
  - Copyright Notice: Electronic Transaction Consultants
  - @(#)
  - Description: Layout for printing a page. This layout simply displays the
    content generated by Oracle report.
  --%>
  
<%@ include file="/jsp/common/Taglibs.jsp" %>

<tiles:get name="content"/>        
