/*
 * Copyright 2009 Electronic Transaction Consultants
 */
package com.etcc.csc.common;


public enum ErrorMessageEnum {
	ERR_CODE_GENERAL(20010, "ERR_CODE_GENERAL"),
	ERR_CODE_INVALID_AGENCY(20011, "ERR_CODE_INVALID_AGENCY"),
	ERR_CODE_INVALID_PLATE(20012, "ERR_CODE_INVALID_PLATE"),
	ERR_CODE_INVALID_PARTY(20013, "ERR_CODE_INVALID_PARTY"),
	ERR_CODE_INVALID_INVOICE(20014, "ERR_CODE_INVALID_INVOICE"),
	ERR_CODE_NO_VIOLATION_QUALIFIES(20015, "ERR_CODE_NO_VIOLATION_QUALIFIES"),
	ERR_CODE_NO_INVOICE_QUALIFIES(20016, "ERR_CODE_NO_INVOICE_QUALIFIES"),
	ERR_CODE_INVALID_PAYMENT_TYPE(20017, "ERR_CODE_INVALID_PAYMENT_TYPE"),
	ERR_CODE_COULD_NOT_APPLY_PAYMENT(20018, "ERR_CODE_COULD_NOT_APPLY_PAYMENT"),
	ERR_CODE_INVALID_PLATE_STATE(20019, "ERR_CODE_INVALID_PLATE_STATE"),
	ERR_CODE_INVALID_CARD_NUMBER(20020, "ERR_CODE_INVALID_CARD_NUMBER"),
	ERR_CODE_INVALID_EXPIRE_DATE(20021, "ERR_CODE_INVALID_EXPIRE_DATE"),
	ERR_CODE_INVALID_ROUTING_INFO(20022, "ERR_CODE_INVALID_ROUTING_INFO"),
	ERR_CODE_PAYPAGEREGISTRATION_ID(20023, "ERR_CODE_PAYPAGEREGISTRATION_ID"),
	ERR_CODE_INVALID_CARDTYPE(20024, "ERR_CODE_INVALID_CARDTYPE"),
	EXPIRATION_DATE_PAS(-20032, "Expiration date past."),
	ERR_CODE_INVALID_ACCOUNT_ID(20025, "ERR_CODE_INVALID_ACCOUNT_ID");
	
	private final int code;
	private final String message;
	private ErrorMessageEnum(final int code, final String message){
		this.code = code;
		this.message = message;
	}
	
	public int getCode() {
		return code;
	}
	
	public String getMessage() {
		return message;
	}
}
