package com.etcc.csc.common;

import java.io.Serializable;

/**
 * Contains error message that may be either generated by the database server or
 * by the application.
 */
public class ErrorMessageDTO implements Serializable {
	private static final long serialVersionUID = -3832898999744141745L;
	private String key;
	private String message;

	public ErrorMessageDTO() {
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getKey() {
		return key;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append("[");
		sb.append("key=");
		sb.append(key);
		sb.append(", message=");
		sb.append(message);
		sb.append("]");
		return sb.toString();
	}

}
