/*
 * Copyright 2010 Electronic Transaction Consultants 
 */
package com.etcc.csc.service;

import java.util.ArrayList;
import java.util.Collection;

import org.jmock.Expectations;
import org.jmock.Mockery;

import com.etcc.csc.dto.VehicleClassDTO;
import com.etcc.csc.dto.VehicleMakeDTO;

/**
 * Creates a test implementation of <tt>VehicleInterface</tt>.
 * @author Stephen Davidson
 * @author Milosh Boroyevich
 */
public class VehicleFactory {

    // Package level. The ServiceFactoryTestImpl can override the package level access to access this method.
    static void loadImpl(ServiceFactoryTestImpl f, final VehicleInterface mocked) {
        Mockery context = f.getMockeryContext();
        try {
            context.checking(new Expectations() {
                {
                    allowing(mocked).getVehicleClasses();
                    will(returnValue(getVehicleClasses()));
                    allowing(mocked).getVehicleMakes();
                    will(returnValue(getVehicleMakes()));
                }
            });
        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            // Should never happen here.
            throw new RuntimeException(e.getMessage(), e);
        }
    }

    private static final String[] autos = 
        new String[] {"Ferari","Lamborghini","Maserati","Porche","Tesla"};

    private static final String[] motorcycles = 
        new String[] {"Harley Davidson","Kawasaki","Yamaha"};
    
    /**
     * Total number of Vehicle Classes generated by this factory.
     */
    public static final short TOTAL_CLASSES = 4;
    /**
     * Total number of Vehicle Makes generated by this factory.
     */
    public static final int TOTAL_MAKES = autos.length + motorcycles.length;

    /**
     * Gets the Test Collection of Vehicle Classes.
     * @return The Test Collection of vehicle Classes.
     */
    public static Collection<VehicleClassDTO> getVehicleClasses() {
        Collection<VehicleClassDTO> result = new ArrayList<VehicleClassDTO>(TOTAL_CLASSES);
        for (short i = 0; i < TOTAL_CLASSES; i++) {
            VehicleClassDTO dto = new VehicleClassDTO();
            dto.setVehicleClassCode(""+i);
            dto.setVehicleClassDescr("Code " + i);
            dto.setVehicleClassLongDescr("Detailed description for code " + i);
            dto.setVehicleClassOrder(i);
            dto.setActiveFlag(true);
            result.add(dto);
        }
        return result;
    }

    /**
     * Gets the Test Collection of Vehicle Makes.
     * @return The Test Collection of vehicle Makes.
     */
    public static Collection<VehicleMakeDTO> getVehicleMakes() {
        Collection<VehicleMakeDTO> result = new ArrayList<VehicleMakeDTO>(autos.length+motorcycles.length);
        for (int i = 0; i < autos.length; i++) {
            VehicleMakeDTO dto = new VehicleMakeDTO();
            dto.setVehicleMake(autos[i]);
            dto.setMotorcycleFlag(false);
            result.add(dto);
        }
        for (int i = 0; i < motorcycles.length; i++) {
            VehicleMakeDTO dto = new VehicleMakeDTO();
            dto.setVehicleMake(motorcycles[i]);
            dto.setMotorcycleFlag(true);
            result.add(dto);
        }
        return result;
    }
}
