# $Id: log4j.properties,v 1.3 2013/12/02 15:51:58 hudsonbuild Exp $
#Default log settings.  Deployed as part of the "Shared" library, so tends to be the one used in general.

# Attach appender CSC to root. Set root level to Level.DEBUG.
#Standard
log4j.rootLogger=INFO,A2
#For Debugging
#log4j.rootLogger=DEBUG,A1,A2

# log warnings and up from Jakarta Struts, Commons etc.
log4j.logger.org.apache=WARN
# log warnings and up from HTMLTable plugin
log4j.logger.com.zubarev=WARN
# log warnings and up from Struts Menu
log4j.logger.net.sf.navigator=WARN
# log INFO and up from XFire & Spring.
log4j.logger.org.codehaus.xfire=INFO
log4j.logger.org.springframework=INFO

# save each downloaded report in its own file (i.e. ../OnlineTagStore/log/revamp/wsreportfile_2009-03-05_153245_2.rlog)
#com.etcc.csc.ws.reports.rlog=DEBUG
com.etcc.csc.ws.reports.rlog=INFO
#Standard
log4j.logger.com.etcc.csc=INFO
log4j.logger.org.mortbay=INFO
#For Debugging
#log4j.logger.com.etcc.csc=ALL
#log4j.logger.org.mortbay=ALL


# A1 is set to be ConsoleAppender sending its output to System.out
log4j.appender.A1=org.apache.log4j.ConsoleAppender


# A1 uses PatternLayout.
log4j.appender.A1.layout=org.apache.log4j.PatternLayout

# The conversion pattern consists of date in ISO8601 format, level,
# thread name, logger name truncated to its rightmost two components
# and left justified to 17 characters, location information consisting
# of file name (padded to 13 characters) and line number, nested
# diagnostic context, the and the application supplied message

log4j.appender.A1.layout.ConversionPattern=%d %-5p [%t] %-17c{2} (%13F:%L) %3x - %m%n

# file appender
log4j.appender.A2=org.apache.log4j.RollingFileAppender
#log4j.appender.A2.Threshold=ALL
#log4j.appender.A2.Threshold=INFO
#Not available with DatedFileAppender
#log4j.appender.A2.DatePattern='.'yyyy-MM-dd
log4j.appender.A2.Append=true
log4j.appender.A2.File=/app/oracle/files/olcsc/olcsc.log
log4j.appender.A2.MaxFileSize=1GB
log4j.appender.A2.MaxBackupIndex=1000



log4j.appender.A2.layout=org.apache.log4j.PatternLayout
log4j.appender.A2.layout.ConversionPattern=%d{MM/dd/yyyy HH:mm:ss}[%-5p] %c{1}: %m%n
