/*
 * Copyright 2009 Electronic Transaction Consultants
 */
package com.etcc.csc.dto;

import java.io.Serializable;

/**
 * Contains error message that may be either generated by the database server or by the application. Based on the
 * ErrorMessageDTO's from the original OLSCSC Services project.
 * 
 * @author Stephen Davidson
 */
public class ErrorMessageDTO implements Serializable {
    /**
     * Unique ID for Serialization with Version number.
     */
    // Do NOT regenerate, to allow compatibility with "foreign" clients, such as Idea.
    private static final long serialVersionUID = 2448005399312112907L;
    

    private String key;
    private String message;

    /**
     * Constructor.
     */
    public ErrorMessageDTO() {
        // end <init>
    }

    /**
     * Constructor.
     * 
     * @param key The error message key.
     * @param message The Message for the error.
     */
    public ErrorMessageDTO(String key, String message) {
        super();
        this.key = key;
        this.message = message;
    }

    public ErrorMessageDTO withMessage(String message) {
    	String[] errorParts=null;
        String errorMessage=null;
        String errorCode=null;
    	if (message!=null && message.contains("~")){
            errorParts = message.split("~");
            errorMessage =errorParts[0];
            errorCode =errorParts[1];
            setMessage(errorMessage);
            setKey(errorCode);
      	}else{
      	   setMessage(message);
      	}
        return this;
    }

    /**
     * Convenience method to convert the messages in a list of ErrorMessagesDTOs to a StringBuilder.  Generally
     * used for logging.  This method is more efficient than {@link java.util.Arrays#toString(Object[])}, which will call toString
     * on each object in the array, copy the contents to a StringBuilder, and then return a new String Object.
     * @param messages The messages to convert.
     * @return StringBuilder representation of the arrays.
     */
    //TODO: Implement public abstract StringBuilder toStringBuilder() at the BaseDTO level, and move this there.
    public static StringBuilder toStringBuilder(ErrorMessageDTO[] messages) {
        StringBuilder sb = new StringBuilder(512);
        if (messages != null && messages.length > 0){
            for (ErrorMessageDTO errorMessageDTO : messages) {
                sb.append(errorMessageDTO.toStringBuilder());
                sb.append(",\n");
            }
            //Drop the last ',' and CR.
            sb.deleteCharAt(sb.length() -1);
            sb.deleteCharAt(sb.length() -1);
        }
        return sb;
    }

    /**
     * Converts this object to a StringBuilder representation for use in String operations, such as logging.
     * @return the value of this object represented by a StringBuilder.
     */
    public StringBuilder toStringBuilder() {
        StringBuilder sb = new StringBuilder();
        sb.append("[");
        sb.append("key=");
        sb.append(this.key);
        sb.append(", message=");
        sb.append(this.message);
        sb.append("]");
        return sb;
    }

    @Override
    public String toString() {
        return toStringBuilder().toString();
    }

    /**
     * @return the key
     */
    public String getKey() {
        return this.key;
        // end getKey
    }

    /**
     * @param key the key to set
     */
    public void setKey(String key) {
        this.key = key;
        // end setKey
    }

    /**
     * @return the message
     */
    public String getMessage() {
        return this.message;
        // end getMessage
    }

    /**
     * @param message the message to set
     */
    public void setMessage(String message) {
        this.message = message;
        // end setMessage
    }
}
