/*
 * Copyright 2010 Electronic Transaction Consultants 
 */
package com.etcc.csc.dto;

import java.sql.SQLException;

/**
 * Data transfer object for passing a report.
 * @author Milosh Boroyevich
 */
public class ReportDTO extends BaseDTO {
    private static final long serialVersionUID = -7895663767387847306L;

    private static final int STRING_BYTE_COUNT = 8;

    /**
     * Contents of the report document represented as a byte array.
     */
    private byte[] bytes;

    public int size() {
        return bytes.length;
    }

    /**
     * Returns a string representation of the specified number of bytes in this report.
     * @param byteCount number of bytes to return
     * @return string of specified number of bytes
     * @see #getBytes()
     */
    public String bytesToString(int byteCount) {
        if (this.bytes == null || byteCount < 1)
            return null;
        int minBytesToPrint = byteCount;
        if (minBytesToPrint > this.bytes.length)
            minBytesToPrint = this.bytes.length;
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < minBytesToPrint; i++) {
            if (i > 0)
                sb.append(", ");
            sb.append(this.bytes[i]);
        }
        return sb.toString();
    }

    /**
     * Returns a string representation of the first {@link #STRING_BYTE_COUNT} bytes in this report.
     * @return string of the first {@link #STRING_BYTE_COUNT} bytes 
     * @see #bytesToString(int)
     */
    public String bytesToString() {
        return bytesToString(STRING_BYTE_COUNT);
    }

    /**
     * @see #bytesToString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("ReportDTO[");
        sb.append("size=").append(this.bytes.length);
        sb.append(", bytes=[").append(bytesToString()).append("]");
        sb.append(", ").append(super.toString()).append("]");
        return sb.toString();
    }

    public void setBytes(byte[] bytes) {
        this.bytes = bytes;
    }

    public byte[] getBytes() {
        return bytes;
    }
 // QC -15178 : modified for monthly statement , plsql might return the pdf file path for pre-existing notifications generated by questmark. 
    public ReportDTO(final byte[] source) {
        if (source != null){
        	this.bytes = source;
        }
    }

	public ReportDTO() {
	}
}
